:global:
  componentName: syn-kube-prometheus
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - kubernetes_1.20
      - kubernetes_1.21
      - kubernetes_1.22
      - openshift
      - thanos

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  makeTarget: test -e instance=${{ matrix.instance }}

docs/antora.yml:
  name: syn-kube-prometheus
  title: syn-kube-prometheus

.gitignore:
  additionalEntries:
    - jsonnetfile.json
