:global:
  componentName: kube-prometheus
  githubUrl: https://github.com/projectsyn/component-kube-prometheus
  feature_goldenTests: true

.github/workflows/test.yaml:
  matrix:
    key: instance
    entries:
      - defaults
      - kubernetes_1.20
      - kubernetes_1.21
      - kubernetes_1.22
      - openshift
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  test_makeTarget: test -e instance=${{ matrix.instance }}

docs/antora.yml:
  name: kube-prometheus
  title: kube-prometheus

.gitignore:
  additionalEntries:
    - jsonnetfile.json
