name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: prometheus

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v4
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
          - kubernetes_1.22
          - multi
          - rewrite-registries
          - thanos
          - cluster-monitoring
          - kubernetes_1.23
          - kubernetes_1.24
          - additional_rules
          - resourcequota
          - kubernetes_1.25
          - grafana-ingress
          - additional_nodeexporter_args
          - grafana-storage
          - additional-netpols
          - kubernetes_1.26
          - kubernetes_1.27
          - kubernetes_1.28
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Compile component
        run: make test -e instance=${{ matrix.instance }}
  golden:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - defaults
          - kubernetes_1.22
          - multi
          - rewrite-registries
          - thanos
          - cluster-monitoring
          - kubernetes_1.23
          - kubernetes_1.24
          - additional_rules
          - resourcequota
          - kubernetes_1.25
          - grafana-ingress
          - additional_nodeexporter_args
          - grafana-storage
          - additional-netpols
          - kubernetes_1.26
          - kubernetes_1.27
          - kubernetes_1.28
    defaults:
      run:
        working-directory: ${{ env.COMPONENT_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.COMPONENT_NAME }}
      - name: Golden diff
        run: make golden-diff -e instance=${{ matrix.instance }}
